### PR TITLE
Fix Pipes Bugs

### LINKED ISSUE #15: [Bug] Invalid code produced when piping operator statement with parentheses into function
## Elixir / OTP Version

use `elixir --version`

## Current Behaviour

While debugging some code I wrote the following:

```elixir
(call(a, b) == 1) |> dbg()
```

`styler` output the following, invalid code:

```elixir
call(a, b) |> ==(1) |> dbg()
```

## Expected Behaviour

I would expect the output to remain unchanged, or resolve to this:

```elixir
dbg(call(a, b) == 1)
```

### PR DESCRIPTION
**Pull request by novaugust**
Closes #15 

- `a |> b` created invalid ast due to `b` having ast `{:b, _meta, nil = _args}`, causing us to create the improper list `[a | nil]`
- `==` was mistakenly not included in the list of math/comparison operators that are valid starts to a pipe

also snuck in another QOL improvement for helping show invalid AST when running tests

### CODE REVIEW

File: test/style/pipes_test.exs [hunk 1]
```diff
@@ -159,11 +159,19 @@ defmodule Styler.Style.PipesTest do
     end
   end
 
-  describe "run on single pipe issues" do
+  describe "single pipe issues" do
     test "fixes single pipe" do
       assert_style("a |> f()", "f(a)")
     end
 
+    test "recognizes `==` as a valid pipe star" do
```
Comment (novaugust) [inline test/style/pipes_test.exs:167]:
```suggestion
    test "recognizes `==` as a valid pipe start" do
```
