### PR TITLE
maintain meta & comment lines when rewriting case/cond to if statements

### LINKED ISSUE #79: block manipulation is cruel to comments
the `if/unless/with` statement manipulation was all implemented under the SingleNode module, which ignores comments (.. because it's suppose to only manipulate single nodes). given that if and unless both swap blocks around without updating lines/comments, comments will end up in the wrong places

here's a tdd:

```ex
    test "moves comments" do
      assert_style(
        """
        if not :ok do
          # do
          do_body
        else
          # else
          else_body
        end
        """,
        """
        if :ok do
          # else
          else_body
        else
          # do
          do_body
        end
        """
      )
    end
```
fails with

```
  1) test if/else moves comments (Styler.Style.SingleNodeTest)
     test/style/single_node_test.exs:671
     Assertion with == failed
     code:  assert styled == expected
     left:  "if :ok do\n  # do\n  # else\n  else_body\nelse\n  do_body\nend"
     right: "if :ok do\n  # else\n  else_body\nelse\n  # do\n  do_body\nend"
     stacktrace:
       test/style/single_node_test.exs:672: (test)
```

a fix would move this multi-node manipulation to its own style (`Blocks`?) and update the line meta of all nodes in the do/else blocks, and likewise move comments within those ranges to their new homes. examples of manipulating line numbers and comment line numbers can be found in the `Defs` style

### PR DESCRIPTION
**Pull request by novaugust**
Fixes #79 for `case` and `cond`. still need to address if/unless/with (with could be pretty tricky!)

### CODE REVIEW

File: test/support/style_case.ex [hunk 1]
```diff
@@ -46,7 +49,10 @@ defmodule Styler.StyleCase do
       end
 
       assert expected == styled
-      {_, restyled, _} = style(styled)
+
+      if @strict do
+        assert styled_ast == expected_ast
+      end
```
Comment (novaugust) [inline test/support/style_case.ex:55]: i think i could've accomplished the same by just adding the comments in sooner... so probably nix this before merging
